---
title: "What Does Reproducible Research Mean for Plant Pathology?"
author: "A. H. Sparks, E. M. Del Ponte, N. J. Grünwald, and Z. Foster"
date: "5 July 2016"
output:
  word_document:
    reference_docx: Phytopathology_Style_Reference.docx
bibliography: bibliography.bib
csl: phytopathology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. Adam H. Sparks: Centre for Crop Health, University of Southern Queensland, 
Toowoomba, Qld 4350, Australia
2. Emerson M. Del Ponte: Universidade Federal de Viçosa, Viçosa, MG, Brasil
3. Niklaus J. Grünwald: Horticultural Crops Research Laboratory, USDA
Agricultural Research Service, Corvallis, OR 97330, USA
4. Zachary Foster: Horticultural Crops Research Laboratory, USDA Agricultural
Research Service, Corvallis, OR 97330, USA

# ABSTRACT

Abstracts are mandatory and limited to one 200 word paragraph.

## WHAT IS REPRODUCICBLE RESEARCH?

**Definitions.** Reproducible research
Replicable research

## WHY REPRODUCIBLE RESEARCH?

## HOW TO MAKE REPRODUCIBLE RESEARCH
Madden et al. [-@Madden2015] supply an *e-**X**tra*\* with repoducible examples
for readers.

## DISCUSSION

## ACKOWLEDGEMENTS

### LITERATURE CITED


